In [2]:
import pinocchio as pin
import numpy as np

In [ ]:
# create SE(3) transformation
#  a 3x3 rotation matrix (Identity here)
R = np.eye(3)

# Define a translation vector
p = np.array([1.0, 2.0, 3.0])

# Create an SE(3) transformation
T = pin.SE3(R, p)

# or

T = pin.SE3(np.array([[1, 0,  0, 0],
                          [0, 0, -1, 0],
                          [0, 1,  0, 3],
                          [0, 0,  0, 1]]))

xi = np.array([1.0, 2.0, 3.0, 1, 0, 1])

In [ ]:
print(pin.log6(T)) # homo ->  [v, w]
print(pin.Jlog6(T)) # homo -> 6 by 6 adj
print(T.homogeneous) # homo
pin.exp6(xi).homogeneous # [v, w] -> homo

w = pin.log3(R) # rot  ->  w
pin.exp3(w) # w  ->  rot

# so(3) and se(3) can be derive by the w and v


print(T.setIdentity)

V = pin.log6(T)
print(V.angular)
print(V.linear)

  v =       0 2.35619 2.35619
  w = 1.5708      0      0

[[ 1.          0.          0.          0.         -0.85619449  1.5       ]
 [ 0.          0.78539816 -0.78539816  1.5         0.          0.        ]
 [ 0.          0.78539816  0.78539816 -0.85619449  0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.        ]
 [ 0.          0.          0.          0.          0.78539816 -0.78539816]
 [ 0.          0.          0.          0.          0.78539816  0.78539816]]
[[ 1.  0.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  1.  0.  3.]
 [ 0.  0.  0.  1.]]
<bound method setIdentity of SE3(array([[ 1.,  0.,  0.,  0.],[ 0.,  0., -1.,  0.],[ 0.,  1.,  0.,  3.],[ 0.,  0.,  0.,  1.]]))>
[1.57079633 0.         0.        ]
[0.         2.35619449 2.35619449]


In [28]:
def so3ToVec(so3mat):
        """Converts an so(3) representation to a 3-vector

        :param so3mat: A 3x3 skew-symmetric matrix
        :return: The 3-vector corresponding to so3mat

        Example Input:
            so3mat = np.array([[ 0, -3,  2],
                               [ 3,  0, -1],
                               [-2,  1,  0]])
        Output:
            np.array([1, 2, 3])
        """
        return np.array([so3mat[2][1], so3mat[0][2], so3mat[1][0]])


so3mat = np.array([[ 0, -3,  2],
                    [ 3,  0, -1],
                    [-2,  1,  0]])
w = so3ToVec(so3mat)
R = pin.exp3(w)


pin.log3(R)

array([-0.67925191, -1.35850382, -2.03775573])