In [6]:
import numpy as np
import torch

ee_pose_w=torch.tensor([[ 1.0100e+00,  3.4628e-10,  1.1491e+00,  1.0000e+00,  5.7377e-17,
          2.2724e-08, -2.2724e-08],
        [-9.9000e-01,  3.4628e-10,  1.1491e+00,  1.0000e+00,  5.7377e-17,
          2.2724e-08, -2.2724e-08]], device='cuda:0')

print(ee_pose_w.shape[0])


2


In [18]:
from pyquaternion import Quaternion
Rot3_matrix=[]
for i in range(0, ee_pose_w.shape[0]):
                
                print(ee_pose_w[i][3:7].tolist())
                myquaternion=Quaternion(ee_pose_w[i][3:7].tolist())
                print("myquaternion: ", myquaternion,"/n")

                Rot3_matrix.append(myquaternion.rotation_matrix) 
                # print("Rot3_matrix: ", myquaternion.rotation_matrix)
Rot3_matrix=np.array(Rot3_matrix)
print("Rot3_matrix: ", Rot3_matrix)
Rot3_matrix=torch.tensor(Rot3_matrix, device='cuda:0')
print("Rot3_matrix: ", Rot3_matrix)


[1.0, 5.737699937793654e-17, 2.272400045910672e-08, -2.272400045910672e-08]
myquaternion:  1.000 +0.000i +0.000j -0.000k /n
[1.0, 5.737699937793654e-17, 2.272400045910672e-08, -2.272400045910672e-08]
myquaternion:  1.000 +0.000i +0.000j -0.000k /n
Rot3_matrix:  [[[ 1.00000000e+00  4.54480009e-08  4.54480009e-08]
  [-4.54480009e-08  1.00000000e+00 -1.14751439e-15]
  [-4.54480009e-08 -9.18006395e-16  1.00000000e+00]]

 [[ 1.00000000e+00  4.54480009e-08  4.54480009e-08]
  [-4.54480009e-08  1.00000000e+00 -1.14751439e-15]
  [-4.54480009e-08 -9.18006395e-16  1.00000000e+00]]]
Rot3_matrix:  tensor([[[ 1.0000e+00,  4.5448e-08,  4.5448e-08],
         [-4.5448e-08,  1.0000e+00, -1.1475e-15],
         [-4.5448e-08, -9.1801e-16,  1.0000e+00]],

        [[ 1.0000e+00,  4.5448e-08,  4.5448e-08],
         [-4.5448e-08,  1.0000e+00, -1.1475e-15],
         [-4.5448e-08, -9.1801e-16,  1.0000e+00]]], device='cuda:0',
       dtype=torch.float64)


In [25]:
import torch

def quaternion_to_rotation_matrix(q):
    """
    Convert a tensor of quaternions (x, y, z, w) to a tensor of 3x3 rotation matrices.
    
    Args:
        q: Tensor of shape (n, 4), each row is (x, y, z, w).
           Assumes q is normalized.
    
    Returns:
        A tensor of shape (n, 3, 3) with the corresponding rotation matrices.
    """
    for i in range(0, q.shape[0]):
                
                    
        # Unpack components assuming (x, y, z, w)
        x, y, z, w = q[i, 0], q[i, 1], q[i, 2], q[i, 3]
        
        R11 = 1 - 2*(y**2 + z**2)
        R12 = 2*(x*y - z*w)
        R13 = 2*(x*z + y*w)
        
        R21 = 2*(x*y + z*w)
        R22 = 1 - 2*(x**2 + z**2)
        R23 = 2*(y*z - x*w)
        
        R31 = 2*(x*z - y*w)
        R32 = 2*(y*z + x*w)
        R33 = 1 - 2*(x**2 + y**2)
        
        R = torch.stack([
                torch.stack([R11, R12, R13], dim=-1),
                torch.stack([R21, R22, R23], dim=-1),
                torch.stack([R31, R32, R33], dim=-1)
            ], dim=1)
        
    return R

# Example usage:
# Suppose you have 5 quaternions in a tensor of shape (5, 4)

ee_pose_w=torch.tensor([[ 1.0100e+00,  3.4628e-10,  1.1491e+00,  1.0000e+00,  5.7377e-17,
          2.2724e-08, -2.2724e-08],
        [-9.9000e-01,  3.4628e-10,  1.1491e+00,  1.0000e+00,  5.7377e-17,
          2.2724e-08, -2.2724e-08]], device='cuda:0')

R_tensor = quaternion_to_rotation_matrix(ee_pose_w)
print(R_tensor)

tensor([[-1.6409,  2.2982, -2.2752],
        [-2.2982, -3.6011, -1.9800],
        [-2.2752,  1.9800, -0.9602]], device='cuda:0')


In [ ]:
self.tf_list:  [array([[1.   , 0.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   , 0.333],
       [0.   , 0.   , 0.   , 1.   ]]), array([[ 1.00000000e+00, -0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  4.89658314e-12,  1.00000000e+00,
         0.00000000e+00],
       [-0.00000000e+00, -1.00000000e+00,  4.89658314e-12,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]]), array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  4.89658314e-12, -1.00000000e+00,
        -3.16000000e-01],
       [ 0.00000000e+00,  1.00000000e+00,  4.89658314e-12,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]]), array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.25000000e-02],
       [ 0.00000000e+00,  4.89658314e-12, -1.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  4.89658314e-12,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]]), array([[ 1.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        -8.25000000e-02],
       [ 0.00000000e+00,  4.89658314e-12,  1.00000000e+00,
         3.84000000e-01],
       [-0.00000000e+00, -1.00000000e+00,  4.89658314e-12,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]]), array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  4.89658314e-12, -1.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  4.89658314e-12,
         0.00000000e+00],
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]]), array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.80000000e-02],
       [ 0.00000000e+00,  4.89658314e-12, -1.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  4.89658314e-12,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]]), array([[1.   , 0.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   , 0.107],
       [0.   , 0.   , 0.   , 1.   ]]), array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [-0.70710678,  0.70710678, -0.        ,  0.        ],
       [-0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])]


In [37]:
import torch

def quat_tensor_to_rot_matrix(tensor: torch.Tensor) -> torch.Tensor:
    """
    Convert a tensor of quaternion data into rotation matrices.
    
    The function assumes that each quaternion is in the form:
        [q_w, q_x, q_y, q_z]
    The expected input shape is either (n, 4) for a batch of quaternions or (4,) for a single quaternion.
    
    Args:
        tensor (torch.Tensor): A tensor of shape (n, 4) or (4,).
 
    Returns:
        torch.Tensor: A tensor of shape (n, 3, 3) containing the corresponding rotation matrices.
    """
    # If a single quaternion is provided (1D tensor), add a batch dimension.
    if tensor.dim() == 1:
        tensor = tensor.unsqueeze(0)  # Now tensor has shape (1, 4)

    # Normalize the quaternion (adding a small epsilon to avoid division by zero)
    q_norm = torch.norm(tensor, dim=1, keepdim=True)
    q_normalized = tensor / (q_norm + 1e-8)

    # Extract quaternion components
    w = q_normalized[:, 0]
    x = q_normalized[:, 1]
    y = q_normalized[:, 2]
    z = q_normalized[:, 3]

    # Compute the rotation matrix elements using the standard conversion formula.
    # For a quaternion (w, x, y, z) the rotation matrix is:
    #
    #   R = [ [1 - 2*(y² + z²),   2*(x*y - w*z),   2*(x*z + w*y)],
    #         [2*(x*y + w*z),     1 - 2*(x² + z²), 2*(y*z - w*x)],
    #         [2*(x*z - w*y),     2*(y*z + w*x),   1 - 2*(x² + y²)] ]
    #
    R11 = 1 - 2 * (y * y + z * z)
    R12 = 2 * (x * y - w * z)
    R13 = 2 * (x * z + w * y)

    R21 = 2 * (x * y + w * z)
    R22 = 1 - 2 * (x * x + z * z)
    R23 = 2 * (y * z - w * x)

    R31 = 2 * (x * z - w * y)
    R32 = 2 * (y * z + w * x)
    R33 = 1 - 2 * (x * x + y * y)

    # Stack the computed components into rotation matrices.
    # Each of R11, R12, ..., R33 has shape (n,), so we first create rows of shape (n, 3)
    row1 = torch.stack([R11, R12, R13], dim=1)
    row2 = torch.stack([R21, R22, R23], dim=1)
    row3 = torch.stack([R31, R32, R33], dim=1)
    
    # Stack the rows to get a final shape of (n, 3, 3)
    rot_matrices = torch.stack([row1, row2, row3], dim=1)
    
    return rot_matrices

# === Example usage ===

# Example 1: Using a batch of quaternions (shape: (n, 4))
ee_pose_w = torch.tensor([
    [1.0000e+00,  5.7377e-17,  2.2724e-08, -2.2724e-08],
    [1.0000e+00,  5.7377e-17,  2.2724e-08, -2.2724e-08]
], device='cuda:0')
R_tensor = quat_tensor_to_rot_matrix(ee_pose_w)
print("Rotation matrices from batch of quaternions:")
print(R_tensor)



Rotation matrices from batch of quaternions:
tensor([[[ 1.0000e+00,  4.5448e-08,  4.5448e-08],
         [-4.5448e-08,  1.0000e+00, -1.1475e-15],
         [-4.5448e-08, -9.1801e-16,  1.0000e+00]],

        [[ 1.0000e+00,  4.5448e-08,  4.5448e-08],
         [-4.5448e-08,  1.0000e+00, -1.1475e-15],
         [-4.5448e-08, -9.1801e-16,  1.0000e+00]]], device='cuda:0')
